// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: laptopInfo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LaptopInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cpu           float64                `protobuf:"fixed64,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Ram           *MemoryUsage           `protobuf:"bytes,3,opt,name=ram,proto3" json:"ram,omitempty"`
	Storages      *MemoryUsage           `protobuf:"bytes,4,opt,name=storages,proto3" json:"storages,omitempty"`
	Network       *Network               `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	Battery       uint32                 `protobuf:"varint,6,opt,name=battery,proto3" json:"battery,omitempty"`
	CreateAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=createAt,proto3" json:"createAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaptopInfo) Reset() {
	*x = LaptopInfo{}
	mi := &file_laptopInfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaptopInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaptopInfo) ProtoMessage() {}

func (x *LaptopInfo) ProtoReflect() protoreflect.Message {
	mi := &file_laptopInfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaptopInfo.ProtoReflect.Descriptor instead.
func (*LaptopInfo) Descriptor() ([]byte, []int) {
	return file_laptopInfo_proto_rawDescGZIP(), []int{0}
}

func (x *LaptopInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LaptopInfo) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *LaptopInfo) GetRam() *MemoryUsage {
	if x != nil {
		return x.Ram
	}
	return nil
}

func (x *LaptopInfo) GetStorages() *MemoryUsage {
	if x != nil {
		return x.Storages
	}
	return nil
}

func (x *LaptopInfo) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *LaptopInfo) GetBattery() uint32 {
	if x != nil {
		return x.Battery
	}
	return 0
}

func (x *LaptopInfo) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

var File_laptopInfo_proto protoreflect.FileDescriptor

const file_laptopInfo_proto_rawDesc = "" +
	"\n" +
	"\x10laptopInfo.proto\x12\x06pcbook\x1a\fmemory.proto\x1a\rnetwork.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x83\x02\n" +
	"\n" +
	"LaptopInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\x01R\x03cpu\x12%\n" +
	"\x03ram\x18\x03 \x01(\v2\x13.pcbook.MemoryUsageR\x03ram\x12/\n" +
	"\bstorages\x18\x04 \x01(\v2\x13.pcbook.MemoryUsageR\bstorages\x12)\n" +
	"\anetwork\x18\x05 \x01(\v2\x0f.pcbook.NetworkR\anetwork\x12\x18\n" +
	"\abattery\x18\x06 \x01(\rR\abattery\x126\n" +
	"\bcreateAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bcreateAtB#Z!github.com/JeongWoo-Seo/pcBook/pbb\x06proto3"

var (
	file_laptopInfo_proto_rawDescOnce sync.Once
	file_laptopInfo_proto_rawDescData []byte
)

func file_laptopInfo_proto_rawDescGZIP() []byte {
	file_laptopInfo_proto_rawDescOnce.Do(func() {
		file_laptopInfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_laptopInfo_proto_rawDesc), len(file_laptopInfo_proto_rawDesc)))
	})
	return file_laptopInfo_proto_rawDescData
}

var file_laptopInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_laptopInfo_proto_goTypes = []any{
	(*LaptopInfo)(nil),            // 0: pcbook.LaptopInfo
	(*MemoryUsage)(nil),           // 1: pcbook.MemoryUsage
	(*Network)(nil),               // 2: pcbook.Network
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_laptopInfo_proto_depIdxs = []int32{
	1, // 0: pcbook.LaptopInfo.ram:type_name -> pcbook.MemoryUsage
	1, // 1: pcbook.LaptopInfo.storages:type_name -> pcbook.MemoryUsage
	2, // 2: pcbook.LaptopInfo.network:type_name -> pcbook.Network
	3, // 3: pcbook.LaptopInfo.createAt:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_laptopInfo_proto_init() }
func file_laptopInfo_proto_init() {
	if File_laptopInfo_proto != nil {
		return
	}
	file_memory_proto_init()
	file_network_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_laptopInfo_proto_rawDesc), len(file_laptopInfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_laptopInfo_proto_goTypes,
		DependencyIndexes: file_laptopInfo_proto_depIdxs,
		MessageInfos:      file_laptopInfo_proto_msgTypes,
	}.Build()
	File_laptopInfo_proto = out.File
	file_laptopInfo_proto_goTypes = nil
	file_laptopInfo_proto_depIdxs = nil
}
